name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      src: ./source

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/andreykarinskiy/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.src}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.src}}
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.src}}

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - run: echo '${{ steps.nbgv.outputs.SemVer2 }}'

    - name: Pack
      run: dotnet pack *.sln --no-restore -o .
      working-directory: ${{env.src}}
      
    - name: Publish
      run: dotnet nuget push *.nupkg --skip-duplicate
      working-directory: ${{env.src}}
